<?php

/*

This file is part of tjbp/countries.

tjbp/countries is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

tjbp/countries is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with tjbp/countries.  If not, see <http://www.gnu.org/licenses/>.

*/

namespace Tjbp\Countries;

use BadMethodCallException;
use OutOfBoundsException;

class Iso3166
{
    /**
     * Database of ISO 3166 data.
     *
     * @var array
     */
    private static $countries = [
        'AF' => [
            'name' => 'Afghanistan',
            'alpha2' => 'AF',
            'alpha3' => 'AFG',
            'numeric3' => '004',
        ],
        'AX' => [
            'name' => "\xc3\x85land Islands",
            'alpha2' => 'AX',
            'alpha3' => 'ALA',
            'numeric3' => '248',
        ],
        'AL' => [
            'name' => 'Albania',
            'alpha2' => 'AL',
            'alpha3' => 'ALB',
            'numeric3' => '008',
        ],
        'DZ' => [
            'name' => 'Algeria',
            'alpha2' => 'DZ',
            'alpha3' => 'DZA',
            'numeric3' => '012',
        ],
        'AS' => [
            'name' => 'American Samoa',
            'alpha2' => 'AS',
            'alpha3' => 'ASM',
            'numeric3' => '016',
        ],
        'AD' => [
            'name' => 'Andorra',
            'alpha2' => 'AD',
            'alpha3' => 'AND',
            'numeric3' => '020',
        ],
        'AO' => [
            'name' => 'Angola',
            'alpha2' => 'AO',
            'alpha3' => 'AGO',
            'numeric3' => '024',
        ],
        'AI' => [
            'name' => 'Anguilla',
            'alpha2' => 'AI',
            'alpha3' => 'AIA',
            'numeric3' => '660',
        ],
        'AQ' => [
            'name' => 'Antarctica',
            'alpha2' => 'AQ',
            'alpha3' => 'ATA',
            'numeric3' => '010',
        ],
        'AG' => [
            'name' => 'Antigua and Barbuda',
            'alpha2' => 'AG',
            'alpha3' => 'ATG',
            'numeric3' => '028',
        ],
        'AR' => [
            'name' => 'Argentina',
            'alpha2' => 'AR',
            'alpha3' => 'ARG',
            'numeric3' => '032',
        ],
        'AM' => [
            'name' => 'Armenia',
            'alpha2' => 'AM',
            'alpha3' => 'ARM',
            'numeric3' => '051',
        ],
        'AW' => [
            'name' => 'Aruba',
            'alpha2' => 'AW',
            'alpha3' => 'ABW',
            'numeric3' => '533',
        ],
        'AU' => [
            'name' => 'Australia',
            'alpha2' => 'AU',
            'alpha3' => 'AUS',
            'numeric3' => '036',
        ],
        'AT' => [
            'name' => 'Austria',
            'alpha2' => 'AT',
            'alpha3' => 'AUT',
            'numeric3' => '040',
        ],
        'AZ' => [
            'name' => 'Azerbaijan',
            'alpha2' => 'AZ',
            'alpha3' => 'AZE',
            'numeric3' => '031',
        ],
        'BS' => [
            'name' => 'Bahamas (the)',
            'alpha2' => 'BS',
            'alpha3' => 'BHS',
            'numeric3' => '044',
        ],
        'BH' => [
            'name' => 'Bahrain',
            'alpha2' => 'BH',
            'alpha3' => 'BHR',
            'numeric3' => '048',
        ],
        'BD' => [
            'name' => 'Bangladesh',
            'alpha2' => 'BD',
            'alpha3' => 'BGD',
            'numeric3' => '050',
        ],
        'BB' => [
            'name' => 'Barbados',
            'alpha2' => 'BB',
            'alpha3' => 'BRB',
            'numeric3' => '052',
        ],
        'BY' => [
            'name' => 'Belarus',
            'alpha2' => 'BY',
            'alpha3' => 'BLR',
            'numeric3' => '112',
        ],
        'BE' => [
            'name' => 'Belgium',
            'alpha2' => 'BE',
            'alpha3' => 'BEL',
            'numeric3' => '056',
        ],
        'BZ' => [
            'name' => 'Belize',
            'alpha2' => 'BZ',
            'alpha3' => 'BLZ',
            'numeric3' => '084',
        ],
        'BJ' => [
            'name' => 'Benin',
            'alpha2' => 'BJ',
            'alpha3' => 'BEN',
            'numeric3' => '204',
        ],
        'BM' => [
            'name' => 'Bermuda',
            'alpha2' => 'BM',
            'alpha3' => 'BMU',
            'numeric3' => '060',
        ],
        'BT' => [
            'name' => 'Bhutan',
            'alpha2' => 'BT',
            'alpha3' => 'BTN',
            'numeric3' => '064',
        ],
        'BO' => [
            'name' => 'Bolivia (Plurinational State of)',
            'alpha2' => 'BO',
            'alpha3' => 'BOL',
            'numeric3' => '068',
        ],
        'BQ' => [
            'name' => 'Bonaire, Sint Eustatius and Saba',
            'alpha2' => 'BQ',
            'alpha3' => 'BES',
            'numeric3' => '535',
        ],
        'BA' => [
            'name' => 'Bosnia and Herzegovina',
            'alpha2' => 'BA',
            'alpha3' => 'BIH',
            'numeric3' => '070',
        ],
        'BW' => [
            'name' => 'Botswana',
            'alpha2' => 'BW',
            'alpha3' => 'BWA',
            'numeric3' => '072',
        ],
        'BV' => [
            'name' => 'Bouvet Island',
            'alpha2' => 'BV',
            'alpha3' => 'BVT',
            'numeric3' => '074',
        ],
        'BR' => [
            'name' => 'Brazil',
            'alpha2' => 'BR',
            'alpha3' => 'BRA',
            'numeric3' => '076',
        ],
        'IO' => [
            'name' => 'British Indian Ocean Territory (the)',
            'alpha2' => 'IO',
            'alpha3' => 'IOT',
            'numeric3' => '086',
        ],
        'BN' => [
            'name' => 'Brunei Darussalam',
            'alpha2' => 'BN',
            'alpha3' => 'BRN',
            'numeric3' => '096',
        ],
        'BG' => [
            'name' => 'Bulgaria',
            'alpha2' => 'BG',
            'alpha3' => 'BGR',
            'numeric3' => '100',
        ],
        'BF' => [
            'name' => 'Burkina Faso',
            'alpha2' => 'BF',
            'alpha3' => 'BFA',
            'numeric3' => '854',
        ],
        'BI' => [
            'name' => 'Burundi',
            'alpha2' => 'BI',
            'alpha3' => 'BDI',
            'numeric3' => '108',
        ],
        'CV' => [
            'name' => 'Cabo Verde',
            'alpha2' => 'CV',
            'alpha3' => 'CPV',
            'numeric3' => '132',
        ],
        'KH' => [
            'name' => 'Cambodia',
            'alpha2' => 'KH',
            'alpha3' => 'KHM',
            'numeric3' => '116',
        ],
        'CM' => [
            'name' => 'Cameroon',
            'alpha2' => 'CM',
            'alpha3' => 'CMR',
            'numeric3' => '120',
        ],
        'CA' => [
            'name' => 'Canada',
            'alpha2' => 'CA',
            'alpha3' => 'CAN',
            'numeric3' => '124',
        ],
        'KY' => [
            'name' => 'Cayman Islands (the)',
            'alpha2' => 'KY',
            'alpha3' => 'CYM',
            'numeric3' => '136',
        ],
        'CF' => [
            'name' => 'Central African Republic (the)',
            'alpha2' => 'CF',
            'alpha3' => 'CAF',
            'numeric3' => '140',
        ],
        'TD' => [
            'name' => 'Chad',
            'alpha2' => 'TD',
            'alpha3' => 'TCD',
            'numeric3' => '148',
        ],
        'CL' => [
            'name' => 'Chile',
            'alpha2' => 'CL',
            'alpha3' => 'CHL',
            'numeric3' => '152',
        ],
        'CN' => [
            'name' => 'China',
            'alpha2' => 'CN',
            'alpha3' => 'CHN',
            'numeric3' => '156',
        ],
        'CX' => [
            'name' => 'Christmas Island',
            'alpha2' => 'CX',
            'alpha3' => 'CXR',
            'numeric3' => '162',
        ],
        'CC' => [
            'name' => 'Cocos (Keeling) Islands (the)',
            'alpha2' => 'CC',
            'alpha3' => 'CCK',
            'numeric3' => '166',
        ],
        'CO' => [
            'name' => 'Colombia',
            'alpha2' => 'CO',
            'alpha3' => 'COL',
            'numeric3' => '170',
        ],
        'KM' => [
            'name' => 'Comoros (the)',
            'alpha2' => 'KM',
            'alpha3' => 'COM',
            'numeric3' => '174',
        ],
        'CD' => [
            'name' => 'Congo (the Democratic Republic of the)',
            'alpha2' => 'CD',
            'alpha3' => 'COD',
            'numeric3' => '180',
        ],
        'CG' => [
            'name' => 'Congo (the)',
            'alpha2' => 'CG',
            'alpha3' => 'COG',
            'numeric3' => '178',
        ],
        'CK' => [
            'name' => 'Cook Islands (the)',
            'alpha2' => 'CK',
            'alpha3' => 'COK',
            'numeric3' => '184',
        ],
        'CR' => [
            'name' => 'Costa Rica',
            'alpha2' => 'CR',
            'alpha3' => 'CRI',
            'numeric3' => '188',
        ],
        'CI' => [
            'name' => "C\xc3\xb4te d'Ivoire",
            'alpha2' => 'CI',
            'alpha3' => 'CIV',
            'numeric3' => '384',
        ],
        'HR' => [
            'name' => 'Croatia',
            'alpha2' => 'HR',
            'alpha3' => 'HRV',
            'numeric3' => '191',
        ],
        'CU' => [
            'name' => 'Cuba',
            'alpha2' => 'CU',
            'alpha3' => 'CUB',
            'numeric3' => '192',
        ],
        'CW' => [
            'name' => "Cura\xc3\xa7ao",
            'alpha2' => 'CW',
            'alpha3' => 'CUW',
            'numeric3' => '531',
        ],
        'CY' => [
            'name' => 'Cyprus',
            'alpha2' => 'CY',
            'alpha3' => 'CYP',
            'numeric3' => '196',
        ],
        'CZ' => [
            'name' => 'Czech Republic (the)',
            'alpha2' => 'CZ',
            'alpha3' => 'CZE',
            'numeric3' => '203',
        ],
        'DK' => [
            'name' => 'Denmark',
            'alpha2' => 'DK',
            'alpha3' => 'DNK',
            'numeric3' => '208',
        ],
        'DJ' => [
            'name' => 'Djibouti',
            'alpha2' => 'DJ',
            'alpha3' => 'DJI',
            'numeric3' => '262',
        ],
        'DM' => [
            'name' => 'Dominica',
            'alpha2' => 'DM',
            'alpha3' => 'DMA',
            'numeric3' => '212',
        ],
        'DO' => [
            'name' => 'Dominican Republic (the)',
            'alpha2' => 'DO',
            'alpha3' => 'DOM',
            'numeric3' => '214',
        ],
        'EC' => [
            'name' => 'Ecuador',
            'alpha2' => 'EC',
            'alpha3' => 'ECU',
            'numeric3' => '218',
        ],
        'EG' => [
            'name' => 'Egypt',
            'alpha2' => 'EG',
            'alpha3' => 'EGY',
            'numeric3' => '818',
        ],
        'SV' => [
            'name' => 'El Salvador',
            'alpha2' => 'SV',
            'alpha3' => 'SLV',
            'numeric3' => '222',
        ],
        'GQ' => [
            'name' => 'Equatorial Guinea',
            'alpha2' => 'GQ',
            'alpha3' => 'GNQ',
            'numeric3' => '226',
        ],
        'ER' => [
            'name' => 'Eritrea',
            'alpha2' => 'ER',
            'alpha3' => 'ERI',
            'numeric3' => '232',
        ],
        'EE' => [
            'name' => 'Estonia',
            'alpha2' => 'EE',
            'alpha3' => 'EST',
            'numeric3' => '233',
        ],
        'ET' => [
            'name' => 'Ethiopia',
            'alpha2' => 'ET',
            'alpha3' => 'ETH',
            'numeric3' => '231',
        ],
        'FK' => [
            'name' => 'Falkland Islands (the) [Malvinas]',
            'alpha2' => 'FK',
            'alpha3' => 'FLK',
            'numeric3' => '238',
        ],
        'FO' => [
            'name' => 'Faroe Islands (the)',
            'alpha2' => 'FO',
            'alpha3' => 'FRO',
            'numeric3' => '234',
        ],
        'FJ' => [
            'name' => 'Fiji',
            'alpha2' => 'FJ',
            'alpha3' => 'FJI',
            'numeric3' => '242',
        ],
        'FI' => [
            'name' => 'Finland',
            'alpha2' => 'FI',
            'alpha3' => 'FIN',
            'numeric3' => '246',
        ],
        'FR' => [
            'name' => 'France',
            'alpha2' => 'FR',
            'alpha3' => 'FRA',
            'numeric3' => '250',
        ],
        'GF' => [
            'name' => 'French Guiana',
            'alpha2' => 'GF',
            'alpha3' => 'GUF',
            'numeric3' => '254',
        ],
        'PF' => [
            'name' => 'French Polynesia',
            'alpha2' => 'PF',
            'alpha3' => 'PYF',
            'numeric3' => '258',
        ],
        'TF' => [
            'name' => 'French Southern Territories (the)',
            'alpha2' => 'TF',
            'alpha3' => 'ATF',
            'numeric3' => '260',
        ],
        'GA' => [
            'name' => 'Gabon',
            'alpha2' => 'GA',
            'alpha3' => 'GAB',
            'numeric3' => '266',
        ],
        'GM' => [
            'name' => 'Gambia (the)',
            'alpha2' => 'GM',
            'alpha3' => 'GMB',
            'numeric3' => '270',
        ],
        'GE' => [
            'name' => 'Georgia',
            'alpha2' => 'GE',
            'alpha3' => 'GEO',
            'numeric3' => '268',
        ],
        'DE' => [
            'name' => 'Germany',
            'alpha2' => 'DE',
            'alpha3' => 'DEU',
            'numeric3' => '276',
        ],
        'GH' => [
            'name' => 'Ghana',
            'alpha2' => 'GH',
            'alpha3' => 'GHA',
            'numeric3' => '288',
        ],
        'GI' => [
            'name' => 'Gibraltar',
            'alpha2' => 'GI',
            'alpha3' => 'GIB',
            'numeric3' => '292',
        ],
        'GR' => [
            'name' => 'Greece',
            'alpha2' => 'GR',
            'alpha3' => 'GRC',
            'numeric3' => '300',
        ],
        'GL' => [
            'name' => 'Greenland',
            'alpha2' => 'GL',
            'alpha3' => 'GRL',
            'numeric3' => '304',
        ],
        'GD' => [
            'name' => 'Grenada',
            'alpha2' => 'GD',
            'alpha3' => 'GRD',
            'numeric3' => '308',
        ],
        'GP' => [
            'name' => 'Guadeloupe',
            'alpha2' => 'GP',
            'alpha3' => 'GLP',
            'numeric3' => '312',
        ],
        'GU' => [
            'name' => 'Guam',
            'alpha2' => 'GU',
            'alpha3' => 'GUM',
            'numeric3' => '316',
        ],
        'GT' => [
            'name' => 'Guatemala',
            'alpha2' => 'GT',
            'alpha3' => 'GTM',
            'numeric3' => '320',
        ],
        'GG' => [
            'name' => 'Guernsey',
            'alpha2' => 'GG',
            'alpha3' => 'GGY',
            'numeric3' => '831',
        ],
        'GN' => [
            'name' => 'Guinea',
            'alpha2' => 'GN',
            'alpha3' => 'GIN',
            'numeric3' => '324',
        ],
        'GW' => [
            'name' => 'Guinea-Bissau',
            'alpha2' => 'GW',
            'alpha3' => 'GNB',
            'numeric3' => '624',
        ],
        'GY' => [
            'name' => 'Guyana',
            'alpha2' => 'GY',
            'alpha3' => 'GUY',
            'numeric3' => '328',
        ],
        'HT' => [
            'name' => 'Haiti',
            'alpha2' => 'HT',
            'alpha3' => 'HTI',
            'numeric3' => '332',
        ],
        'HM' => [
            'name' => 'Heard Island and McDonald Islands',
            'alpha2' => 'HM',
            'alpha3' => 'HMD',
            'numeric3' => '334',
        ],
        'VA' => [
            'name' => 'Holy See (the)',
            'alpha2' => 'VA',
            'alpha3' => 'VAT',
            'numeric3' => '336',
        ],
        'HN' => [
            'name' => 'Honduras',
            'alpha2' => 'HN',
            'alpha3' => 'HND',
            'numeric3' => '340',
        ],
        'HK' => [
            'name' => 'Hong Kong',
            'alpha2' => 'HK',
            'alpha3' => 'HKG',
            'numeric3' => '344',
        ],
        'HU' => [
            'name' => 'Hungary',
            'alpha2' => 'HU',
            'alpha3' => 'HUN',
            'numeric3' => '348',
        ],
        'IS' => [
            'name' => 'Iceland',
            'alpha2' => 'IS',
            'alpha3' => 'ISL',
            'numeric3' => '352',
        ],
        'IN' => [
            'name' => 'India',
            'alpha2' => 'IN',
            'alpha3' => 'IND',
            'numeric3' => '356',
        ],
        'ID' => [
            'name' => 'Indonesia',
            'alpha2' => 'ID',
            'alpha3' => 'IDN',
            'numeric3' => '360',
        ],
        'IR' => [
            'name' => 'Iran (Islamic Republic of)',
            'alpha2' => 'IR',
            'alpha3' => 'IRN',
            'numeric3' => '364',
        ],
        'IQ' => [
            'name' => 'Iraq',
            'alpha2' => 'IQ',
            'alpha3' => 'IRQ',
            'numeric3' => '368',
        ],
        'IE' => [
            'name' => 'Ireland',
            'alpha2' => 'IE',
            'alpha3' => 'IRL',
            'numeric3' => '372',
        ],
        'IM' => [
            'name' => 'Isle of Man',
            'alpha2' => 'IM',
            'alpha3' => 'IMN',
            'numeric3' => '833',
        ],
        'IL' => [
            'name' => 'Israel',
            'alpha2' => 'IL',
            'alpha3' => 'ISR',
            'numeric3' => '376',
        ],
        'IT' => [
            'name' => 'Italy',
            'alpha2' => 'IT',
            'alpha3' => 'ITA',
            'numeric3' => '380',
        ],
        'JM' => [
            'name' => 'Jamaica',
            'alpha2' => 'JM',
            'alpha3' => 'JAM',
            'numeric3' => '388',
        ],
        'JP' => [
            'name' => 'Japan',
            'alpha2' => 'JP',
            'alpha3' => 'JPN',
            'numeric3' => '392',
        ],
        'JE' => [
            'name' => 'Jersey',
            'alpha2' => 'JE',
            'alpha3' => 'JEY',
            'numeric3' => '832',
        ],
        'JO' => [
            'name' => 'Jordan',
            'alpha2' => 'JO',
            'alpha3' => 'JOR',
            'numeric3' => '400',
        ],
        'KZ' => [
            'name' => 'Kazakhstan',
            'alpha2' => 'KZ',
            'alpha3' => 'KAZ',
            'numeric3' => '398',
        ],
        'KE' => [
            'name' => 'Kenya',
            'alpha2' => 'KE',
            'alpha3' => 'KEN',
            'numeric3' => '404',
        ],
        'KI' => [
            'name' => 'Kiribati',
            'alpha2' => 'KI',
            'alpha3' => 'KIR',
            'numeric3' => '296',
        ],
        'KP' => [
            'name' => 'Korea (the Democratic People\'s Republic of)',
            'alpha2' => 'KP',
            'alpha3' => 'PRK',
            'numeric3' => '408',
        ],
        'KR' => [
            'name' => 'Korea (the Republic of)',
            'alpha2' => 'KR',
            'alpha3' => 'KOR',
            'numeric3' => '410',
        ],
        'KW' => [
            'name' => 'Kuwait',
            'alpha2' => 'KW',
            'alpha3' => 'KWT',
            'numeric3' => '414',
        ],
        'KG' => [
            'name' => 'Kyrgyzstan',
            'alpha2' => 'KG',
            'alpha3' => 'KGZ',
            'numeric3' => '417',
        ],
        'LA' => [
            'name' => 'Lao People\'s Democratic Republic (the)',
            'alpha2' => 'LA',
            'alpha3' => 'LAO',
            'numeric3' => '418',
        ],
        'LV' => [
            'name' => 'Latvia',
            'alpha2' => 'LV',
            'alpha3' => 'LVA',
            'numeric3' => '428',
        ],
        'LB' => [
            'name' => 'Lebanon',
            'alpha2' => 'LB',
            'alpha3' => 'LBN',
            'numeric3' => '422',
        ],
        'LS' => [
            'name' => 'Lesotho',
            'alpha2' => 'LS',
            'alpha3' => 'LSO',
            'numeric3' => '426',
        ],
        'LR' => [
            'name' => 'Liberia',
            'alpha2' => 'LR',
            'alpha3' => 'LBR',
            'numeric3' => '430',
        ],
        'LY' => [
            'name' => 'Libya',
            'alpha2' => 'LY',
            'alpha3' => 'LBY',
            'numeric3' => '434',
        ],
        'LI' => [
            'name' => 'Liechtenstein',
            'alpha2' => 'LI',
            'alpha3' => 'LIE',
            'numeric3' => '438',
        ],
        'LT' => [
            'name' => 'Lithuania',
            'alpha2' => 'LT',
            'alpha3' => 'LTU',
            'numeric3' => '440',
        ],
        'LU' => [
            'name' => 'Luxembourg',
            'alpha2' => 'LU',
            'alpha3' => 'LUX',
            'numeric3' => '442',
        ],
        'MO' => [
            'name' => 'Macao',
            'alpha2' => 'MO',
            'alpha3' => 'MAC',
            'numeric3' => '446',
        ],
        'MK' => [
            'name' => 'Macedonia (the former Yugoslav Republic of)',
            'alpha2' => 'MK',
            'alpha3' => 'MKD',
            'numeric3' => '807',
        ],
        'MG' => [
            'name' => 'Madagascar',
            'alpha2' => 'MG',
            'alpha3' => 'MDG',
            'numeric3' => '450',
        ],
        'MW' => [
            'name' => 'Malawi',
            'alpha2' => 'MW',
            'alpha3' => 'MWI',
            'numeric3' => '454',
        ],
        'MY' => [
            'name' => 'Malaysia',
            'alpha2' => 'MY',
            'alpha3' => 'MYS',
            'numeric3' => '458',
        ],
        'MV' => [
            'name' => 'Maldives',
            'alpha2' => 'MV',
            'alpha3' => 'MDV',
            'numeric3' => '462',
        ],
        'ML' => [
            'name' => 'Mali',
            'alpha2' => 'ML',
            'alpha3' => 'MLI',
            'numeric3' => '466',
        ],
        'MT' => [
            'name' => 'Malta',
            'alpha2' => 'MT',
            'alpha3' => 'MLT',
            'numeric3' => '470',
        ],
        'MH' => [
            'name' => 'Marshall Islands (the)',
            'alpha2' => 'MH',
            'alpha3' => 'MHL',
            'numeric3' => '584',
        ],
        'MQ' => [
            'name' => 'Martinique',
            'alpha2' => 'MQ',
            'alpha3' => 'MTQ',
            'numeric3' => '474',
        ],
        'MR' => [
            'name' => 'Mauritania',
            'alpha2' => 'MR',
            'alpha3' => 'MRT',
            'numeric3' => '478',
        ],
        'MU' => [
            'name' => 'Mauritius',
            'alpha2' => 'MU',
            'alpha3' => 'MUS',
            'numeric3' => '480',
        ],
        'YT' => [
            'name' => 'Mayotte',
            'alpha2' => 'YT',
            'alpha3' => 'MYT',
            'numeric3' => '175',
        ],
        'MX' => [
            'name' => 'Mexico',
            'alpha2' => 'MX',
            'alpha3' => 'MEX',
            'numeric3' => '484',
        ],
        'FM' => [
            'name' => 'Micronesia (Federated States of)',
            'alpha2' => 'FM',
            'alpha3' => 'FSM',
            'numeric3' => '583',
        ],
        'MD' => [
            'name' => 'Moldova (the Republic of)',
            'alpha2' => 'MD',
            'alpha3' => 'MDA',
            'numeric3' => '498',
        ],
        'MC' => [
            'name' => 'Monaco',
            'alpha2' => 'MC',
            'alpha3' => 'MCO',
            'numeric3' => '492',
        ],
        'MN' => [
            'name' => 'Mongolia',
            'alpha2' => 'MN',
            'alpha3' => 'MNG',
            'numeric3' => '496',
        ],
        'ME' => [
            'name' => 'Montenegro',
            'alpha2' => 'ME',
            'alpha3' => 'MNE',
            'numeric3' => '499',
        ],
        'MS' => [
            'name' => 'Montserrat',
            'alpha2' => 'MS',
            'alpha3' => 'MSR',
            'numeric3' => '500',
        ],
        'MA' => [
            'name' => 'Morocco',
            'alpha2' => 'MA',
            'alpha3' => 'MAR',
            'numeric3' => '504',
        ],
        'MZ' => [
            'name' => 'Mozambique',
            'alpha2' => 'MZ',
            'alpha3' => 'MOZ',
            'numeric3' => '508',
        ],
        'MM' => [
            'name' => 'Myanmar',
            'alpha2' => 'MM',
            'alpha3' => 'MMR',
            'numeric3' => '104',
        ],
        'NA' => [
            'name' => 'Namibia',
            'alpha2' => 'NA',
            'alpha3' => 'NAM',
            'numeric3' => '516',
        ],
        'NR' => [
            'name' => 'Nauru',
            'alpha2' => 'NR',
            'alpha3' => 'NRU',
            'numeric3' => '520',
        ],
        'NP' => [
            'name' => 'Nepal',
            'alpha2' => 'NP',
            'alpha3' => 'NPL',
            'numeric3' => '524',
        ],
        'NL' => [
            'name' => 'Netherlands (the)',
            'alpha2' => 'NL',
            'alpha3' => 'NLD',
            'numeric3' => '528',
        ],
        'NC' => [
            'name' => 'New Caledonia',
            'alpha2' => 'NC',
            'alpha3' => 'NCL',
            'numeric3' => '540',
        ],
        'NZ' => [
            'name' => 'New Zealand',
            'alpha2' => 'NZ',
            'alpha3' => 'NZL',
            'numeric3' => '554',
        ],
        'NI' => [
            'name' => 'Nicaragua',
            'alpha2' => 'NI',
            'alpha3' => 'NIC',
            'numeric3' => '558',
        ],
        'NE' => [
            'name' => 'Niger (the)',
            'alpha2' => 'NE',
            'alpha3' => 'NER',
            'numeric3' => '562',
        ],
        'NG' => [
            'name' => 'Nigeria',
            'alpha2' => 'NG',
            'alpha3' => 'NGA',
            'numeric3' => '566',
        ],
        'NU' => [
            'name' => 'Niue',
            'alpha2' => 'NU',
            'alpha3' => 'NIU',
            'numeric3' => '570',
        ],
        'NF' => [
            'name' => 'Norfolk Island',
            'alpha2' => 'NF',
            'alpha3' => 'NFK',
            'numeric3' => '574',
        ],
        'MP' => [
            'name' => 'Northern Mariana Islands (the)',
            'alpha2' => 'MP',
            'alpha3' => 'MNP',
            'numeric3' => '580',
        ],
        'NO' => [
            'name' => 'Norway',
            'alpha2' => 'NO',
            'alpha3' => 'NOR',
            'numeric3' => '578',
        ],
        'OM' => [
            'name' => 'Oman',
            'alpha2' => 'OM',
            'alpha3' => 'OMN',
            'numeric3' => '512',
        ],
        'PK' => [
            'name' => 'Pakistan',
            'alpha2' => 'PK',
            'alpha3' => 'PAK',
            'numeric3' => '586',
        ],
        'PW' => [
            'name' => 'Palau',
            'alpha2' => 'PW',
            'alpha3' => 'PLW',
            'numeric3' => '585',
        ],
        'PS' => [
            'name' => 'Palestine, State of',
            'alpha2' => 'PS',
            'alpha3' => 'PSE',
            'numeric3' => '275',
        ],
        'PA' => [
            'name' => 'Panama',
            'alpha2' => 'PA',
            'alpha3' => 'PAN',
            'numeric3' => '591',
        ],
        'PG' => [
            'name' => 'Papua New Guinea',
            'alpha2' => 'PG',
            'alpha3' => 'PNG',
            'numeric3' => '598',
        ],
        'PY' => [
            'name' => 'Paraguay',
            'alpha2' => 'PY',
            'alpha3' => 'PRY',
            'numeric3' => '600',
        ],
        'PE' => [
            'name' => 'Peru',
            'alpha2' => 'PE',
            'alpha3' => 'PER',
            'numeric3' => '604',
        ],
        'PH' => [
            'name' => 'Philippines (the)',
            'alpha2' => 'PH',
            'alpha3' => 'PHL',
            'numeric3' => '608',
        ],
        'PN' => [
            'name' => 'Pitcairn',
            'alpha2' => 'PN',
            'alpha3' => 'PCN',
            'numeric3' => '612',
        ],
        'PL' => [
            'name' => 'Poland',
            'alpha2' => 'PL',
            'alpha3' => 'POL',
            'numeric3' => '616',
        ],
        'PT' => [
            'name' => 'Portugal',
            'alpha2' => 'PT',
            'alpha3' => 'PRT',
            'numeric3' => '620',
        ],
        'PR' => [
            'name' => 'Puerto Rico',
            'alpha2' => 'PR',
            'alpha3' => 'PRI',
            'numeric3' => '630',
        ],
        'QA' => [
            'name' => 'Qatar',
            'alpha2' => 'QA',
            'alpha3' => 'QAT',
            'numeric3' => '634',
        ],
        'RE' => [
            'name' => "R\xc3\xa9union",
            'alpha2' => 'RE',
            'alpha3' => 'REU',
            'numeric3' => '638',
        ],
        'RO' => [
            'name' => 'Romania',
            'alpha2' => 'RO',
            'alpha3' => 'ROU',
            'numeric3' => '642',
        ],
        'RU' => [
            'name' => 'Russian Federation (the)',
            'alpha2' => 'RU',
            'alpha3' => 'RUS',
            'numeric3' => '643',
        ],
        'RW' => [
            'name' => 'Rwanda',
            'alpha2' => 'RW',
            'alpha3' => 'RWA',
            'numeric3' => '646',
        ],
        'BL' => [
            'name' => "Saint Barth\xc3\xa9lemy",
            'alpha2' => 'BL',
            'alpha3' => 'BLM',
            'numeric3' => '652',
        ],
        'SH' => [
            'name' => 'Saint Helena, Ascension and Tristan da Cunha',
            'alpha2' => 'SH',
            'alpha3' => 'SHN',
            'numeric3' => '654',
        ],
        'KN' => [
            'name' => 'Saint Kitts and Nevis',
            'alpha2' => 'KN',
            'alpha3' => 'KNA',
            'numeric3' => '659',
        ],
        'LC' => [
            'name' => 'Saint Lucia',
            'alpha2' => 'LC',
            'alpha3' => 'LCA',
            'numeric3' => '662',
        ],
        'MF' => [
            'name' => 'Saint Martin (French part)',
            'alpha2' => 'MF',
            'alpha3' => 'MAF',
            'numeric3' => '663',
        ],
        'PM' => [
            'name' => 'Saint Pierre and Miquelon',
            'alpha2' => 'PM',
            'alpha3' => 'SPM',
            'numeric3' => '666',
        ],
        'VC' => [
            'name' => 'Saint Vincent and the Grenadines',
            'alpha2' => 'VC',
            'alpha3' => 'VCT',
            'numeric3' => '670',
        ],
        'WS' => [
            'name' => 'Samoa',
            'alpha2' => 'WS',
            'alpha3' => 'WSM',
            'numeric3' => '882',
        ],
        'SM' => [
            'name' => 'San Marino',
            'alpha2' => 'SM',
            'alpha3' => 'SMR',
            'numeric3' => '674',
        ],
        'ST' => [
            'name' => 'Sao Tome and Principe',
            'alpha2' => 'ST',
            'alpha3' => 'STP',
            'numeric3' => '678',
        ],
        'SA' => [
            'name' => 'Saudi Arabia',
            'alpha2' => 'SA',
            'alpha3' => 'SAU',
            'numeric3' => '682',
        ],
        'SN' => [
            'name' => 'Senegal',
            'alpha2' => 'SN',
            'alpha3' => 'SEN',
            'numeric3' => '686',
        ],
        'RS' => [
            'name' => 'Serbia',
            'alpha2' => 'RS',
            'alpha3' => 'SRB',
            'numeric3' => '688',
        ],
        'SC' => [
            'name' => 'Seychelles',
            'alpha2' => 'SC',
            'alpha3' => 'SYC',
            'numeric3' => '690',
        ],
        'SL' => [
            'name' => 'Sierra Leone',
            'alpha2' => 'SL',
            'alpha3' => 'SLE',
            'numeric3' => '694',
        ],
        'SG' => [
            'name' => 'Singapore',
            'alpha2' => 'SG',
            'alpha3' => 'SGP',
            'numeric3' => '702',
        ],
        'SX' => [
            'name' => 'Sint Maarten (Dutch part)',
            'alpha2' => 'SX',
            'alpha3' => 'SXM',
            'numeric3' => '534',
        ],
        'SK' => [
            'name' => 'Slovakia',
            'alpha2' => 'SK',
            'alpha3' => 'SVK',
            'numeric3' => '703',
        ],
        'SI' => [
            'name' => 'Slovenia',
            'alpha2' => 'SI',
            'alpha3' => 'SVN',
            'numeric3' => '705',
        ],
        'SB' => [
            'name' => 'Solomon Islands',
            'alpha2' => 'SB',
            'alpha3' => 'SLB',
            'numeric3' => '090',
        ],
        'SO' => [
            'name' => 'Somalia',
            'alpha2' => 'SO',
            'alpha3' => 'SOM',
            'numeric3' => '706',
        ],
        'ZA' => [
            'name' => 'South Africa',
            'alpha2' => 'ZA',
            'alpha3' => 'ZAF',
            'numeric3' => '710',
        ],
        'GS' => [
            'name' => 'South Georgia and the South Sandwich Islands',
            'alpha2' => 'GS',
            'alpha3' => 'SGS',
            'numeric3' => '239',
        ],
        'SS' => [
            'name' => 'South Sudan',
            'alpha2' => 'SS',
            'alpha3' => 'SSD',
            'numeric3' => '728',
        ],
        'ES' => [
            'name' => 'Spain',
            'alpha2' => 'ES',
            'alpha3' => 'ESP',
            'numeric3' => '724',
        ],
        'LK' => [
            'name' => 'Sri Lanka',
            'alpha2' => 'LK',
            'alpha3' => 'LKA',
            'numeric3' => '144',
        ],
        'SD' => [
            'name' => 'Sudan (the)',
            'alpha2' => 'SD',
            'alpha3' => 'SDN',
            'numeric3' => '729',
        ],
        'SR' => [
            'name' => 'Suriname',
            'alpha2' => 'SR',
            'alpha3' => 'SUR',
            'numeric3' => '740',
        ],
        'SJ' => [
            'name' => 'Svalbard and Jan Mayen',
            'alpha2' => 'SJ',
            'alpha3' => 'SJM',
            'numeric3' => '744',
        ],
        'SZ' => [
            'name' => 'Swaziland',
            'alpha2' => 'SZ',
            'alpha3' => 'SWZ',
            'numeric3' => '748',
        ],
        'SE' => [
            'name' => 'Sweden',
            'alpha2' => 'SE',
            'alpha3' => 'SWE',
            'numeric3' => '752',
        ],
        'CH' => [
            'name' => 'Switzerland',
            'alpha2' => 'CH',
            'alpha3' => 'CHE',
            'numeric3' => '756',
        ],
        'SY' => [
            'name' => 'Syrian Arab Republic',
            'alpha2' => 'SY',
            'alpha3' => 'SYR',
            'numeric3' => '760',
        ],
        'TW' => [
            'name' => 'Taiwan (Province of China)',
            'alpha2' => 'TW',
            'alpha3' => 'TWN',
            'numeric3' => '158',
        ],
        'TJ' => [
            'name' => 'Tajikistan',
            'alpha2' => 'TJ',
            'alpha3' => 'TJK',
            'numeric3' => '762',
        ],
        'TZ' => [
            'name' => 'Tanzania, United Republic of',
            'alpha2' => 'TZ',
            'alpha3' => 'TZA',
            'numeric3' => '834',
        ],
        'TH' => [
            'name' => 'Thailand',
            'alpha2' => 'TH',
            'alpha3' => 'THA',
            'numeric3' => '764',
        ],
        'TL' => [
            'name' => 'Timor-Leste',
            'alpha2' => 'TL',
            'alpha3' => 'TLS',
            'numeric3' => '626',
        ],
        'TG' => [
            'name' => 'Togo',
            'alpha2' => 'TG',
            'alpha3' => 'TGO',
            'numeric3' => '768',
        ],
        'TK' => [
            'name' => 'Tokelau',
            'alpha2' => 'TK',
            'alpha3' => 'TKL',
            'numeric3' => '772',
        ],
        'TO' => [
            'name' => 'Tonga',
            'alpha2' => 'TO',
            'alpha3' => 'TON',
            'numeric3' => '776',
        ],
        'TT' => [
            'name' => 'Trinidad and Tobago',
            'alpha2' => 'TT',
            'alpha3' => 'TTO',
            'numeric3' => '780',
        ],
        'TN' => [
            'name' => 'Tunisia',
            'alpha2' => 'TN',
            'alpha3' => 'TUN',
            'numeric3' => '788',
        ],
        'TR' => [
            'name' => 'Turkey',
            'alpha2' => 'TR',
            'alpha3' => 'TUR',
            'numeric3' => '792',
        ],
        'TM' => [
            'name' => 'Turkmenistan',
            'alpha2' => 'TM',
            'alpha3' => 'TKM',
            'numeric3' => '795',
        ],
        'TC' => [
            'name' => 'Turks and Caicos Islands (the)',
            'alpha2' => 'TC',
            'alpha3' => 'TCA',
            'numeric3' => '796',
        ],
        'TV' => [
            'name' => 'Tuvalu',
            'alpha2' => 'TV',
            'alpha3' => 'TUV',
            'numeric3' => '798',
        ],
        'UG' => [
            'name' => 'Uganda',
            'alpha2' => 'UG',
            'alpha3' => 'UGA',
            'numeric3' => '800',
        ],
        'UA' => [
            'name' => 'Ukraine',
            'alpha2' => 'UA',
            'alpha3' => 'UKR',
            'numeric3' => '804',
        ],
        'AE' => [
            'name' => 'United Arab Emirates (the)',
            'alpha2' => 'AE',
            'alpha3' => 'ARE',
            'numeric3' => '784',
        ],
        'GB' => [
            'name' => 'United Kingdom of Great Britain and Northern Ireland (the)',
            'alpha2' => 'GB',
            'alpha3' => 'GBR',
            'numeric3' => '826',
        ],
        'UM' => [
            'name' => 'United States Minor Outlying Islands (the)',
            'alpha2' => 'UM',
            'alpha3' => 'UMI',
            'numeric3' => '581',
        ],
        'US' => [
            'name' => 'United States of America (the)',
            'alpha2' => 'US',
            'alpha3' => 'USA',
            'numeric3' => '840',
        ],
        'UY' => [
            'name' => 'Uruguay',
            'alpha2' => 'UY',
            'alpha3' => 'URY',
            'numeric3' => '858',
        ],
        'UZ' => [
            'name' => 'Uzbekistan',
            'alpha2' => 'UZ',
            'alpha3' => 'UZB',
            'numeric3' => '860',
        ],
        'VU' => [
            'name' => 'Vanuatu',
            'alpha2' => 'VU',
            'alpha3' => 'VUT',
            'numeric3' => '548',
        ],
        'VE' => [
            'name' => 'Venezuela (Bolivarian Republic of)',
            'alpha2' => 'VE',
            'alpha3' => 'VEN',
            'numeric3' => '862',
        ],
        'VN' => [
            'name' => 'Viet Nam',
            'alpha2' => 'VN',
            'alpha3' => 'VNM',
            'numeric3' => '704',
        ],
        'VG' => [
            'name' => 'Virgin Islands (British)',
            'alpha2' => 'VG',
            'alpha3' => 'VGB',
            'numeric3' => '092',
        ],
        'VI' => [
            'name' => 'Virgin Islands (U.S.)',
            'alpha2' => 'VI',
            'alpha3' => 'VIR',
            'numeric3' => '850',
        ],
        'WF' => [
            'name' => 'Wallis and Futuna',
            'alpha2' => 'WF',
            'alpha3' => 'WLF',
            'numeric3' => '876',
        ],
        'EH' => [
            'name' => 'Western Sahara*',
            'alpha2' => 'EH',
            'alpha3' => 'ESH',
            'numeric3' => '732',
        ],
        'YE' => [
            'name' => 'Yemen',
            'alpha2' => 'YE',
            'alpha3' => 'YEM',
            'numeric3' => '887',
        ],
        'ZM' => [
            'name' => 'Zambia',
            'alpha2' => 'ZM',
            'alpha3' => 'ZMB',
            'numeric3' => '894',
        ],
        'ZW' => [
            'name' => 'Zimbabwe',
            'alpha2' => 'ZW',
            'alpha3' => 'ZWE',
            'numeric3' => '716',
        ],
    ];

    /**
     * Index of alpha3 codes to speed the lookup.
     *
     * @var array
     */
    private static $alpha3Index = [
        'AFG' => 'AF',
        'ALA' => 'AX',
        'ALB' => 'AL',
        'DZA' => 'DZ',
        'ASM' => 'AS',
        'AND' => 'AD',
        'AGO' => 'AO',
        'AIA' => 'AI',
        'ATA' => 'AQ',
        'ATG' => 'AG',
        'ARG' => 'AR',
        'ARM' => 'AM',
        'ABW' => 'AW',
        'AUS' => 'AU',
        'AUT' => 'AT',
        'AZE' => 'AZ',
        'BHS' => 'BS',
        'BHR' => 'BH',
        'BGD' => 'BD',
        'BRB' => 'BB',
        'BLR' => 'BY',
        'BEL' => 'BE',
        'BLZ' => 'BZ',
        'BEN' => 'BJ',
        'BMU' => 'BM',
        'BTN' => 'BT',
        'BOL' => 'BO',
        'BES' => 'BQ',
        'BIH' => 'BA',
        'BWA' => 'BW',
        'BVT' => 'BV',
        'BRA' => 'BR',
        'IOT' => 'IO',
        'BRN' => 'BN',
        'BGR' => 'BG',
        'BFA' => 'BF',
        'BDI' => 'BI',
        'CPV' => 'CV',
        'KHM' => 'KH',
        'CMR' => 'CM',
        'CAN' => 'CA',
        'CYM' => 'KY',
        'CAF' => 'CF',
        'TCD' => 'TD',
        'CHL' => 'CL',
        'CHN' => 'CN',
        'CXR' => 'CX',
        'CCK' => 'CC',
        'COL' => 'CO',
        'COM' => 'KM',
        'COD' => 'CD',
        'COG' => 'CG',
        'COK' => 'CK',
        'CRI' => 'CR',
        'CIV' => 'CI',
        'HRV' => 'HR',
        'CUB' => 'CU',
        'CUW' => 'CW',
        'CYP' => 'CY',
        'CZE' => 'CZ',
        'DNK' => 'DK',
        'DJI' => 'DJ',
        'DMA' => 'DM',
        'DOM' => 'DO',
        'ECU' => 'EC',
        'EGY' => 'EG',
        'SLV' => 'SV',
        'GNQ' => 'GQ',
        'ERI' => 'ER',
        'EST' => 'EE',
        'ETH' => 'ET',
        'FLK' => 'FK',
        'FRO' => 'FO',
        'FJI' => 'FJ',
        'FIN' => 'FI',
        'FRA' => 'FR',
        'GUF' => 'GF',
        'PYF' => 'PF',
        'ATF' => 'TF',
        'GAB' => 'GA',
        'GMB' => 'GM',
        'GEO' => 'GE',
        'DEU' => 'DE',
        'GHA' => 'GH',
        'GIB' => 'GI',
        'GRC' => 'GR',
        'GRL' => 'GL',
        'GRD' => 'GD',
        'GLP' => 'GP',
        'GUM' => 'GU',
        'GTM' => 'GT',
        'GGY' => 'GG',
        'GIN' => 'GN',
        'GNB' => 'GW',
        'GUY' => 'GY',
        'HTI' => 'HT',
        'HMD' => 'HM',
        'VAT' => 'VA',
        'HND' => 'HN',
        'HKG' => 'HK',
        'HUN' => 'HU',
        'ISL' => 'IS',
        'IND' => 'IN',
        'IDN' => 'ID',
        'IRN' => 'IR',
        'IRQ' => 'IQ',
        'IRL' => 'IE',
        'IMN' => 'IM',
        'ISR' => 'IL',
        'ITA' => 'IT',
        'JAM' => 'JM',
        'JPN' => 'JP',
        'JEY' => 'JE',
        'JOR' => 'JO',
        'KAZ' => 'KZ',
        'KEN' => 'KE',
        'KIR' => 'KI',
        'PRK' => 'KP',
        'KOR' => 'KR',
        'KWT' => 'KW',
        'KGZ' => 'KG',
        'LAO' => 'LA',
        'LVA' => 'LV',
        'LBN' => 'LB',
        'LSO' => 'LS',
        'LBR' => 'LR',
        'LBY' => 'LY',
        'LIE' => 'LI',
        'LTU' => 'LT',
        'LUX' => 'LU',
        'MAC' => 'MO',
        'MKD' => 'MK',
        'MDG' => 'MG',
        'MWI' => 'MW',
        'MYS' => 'MY',
        'MDV' => 'MV',
        'MLI' => 'ML',
        'MLT' => 'MT',
        'MHL' => 'MH',
        'MTQ' => 'MQ',
        'MRT' => 'MR',
        'MUS' => 'MU',
        'MYT' => 'YT',
        'MEX' => 'MX',
        'FSM' => 'FM',
        'MDA' => 'MD',
        'MCO' => 'MC',
        'MNG' => 'MN',
        'MNE' => 'ME',
        'MSR' => 'MS',
        'MAR' => 'MA',
        'MOZ' => 'MZ',
        'MMR' => 'MM',
        'NAM' => 'NA',
        'NRU' => 'NR',
        'NPL' => 'NP',
        'NLD' => 'NL',
        'NCL' => 'NC',
        'NZL' => 'NZ',
        'NIC' => 'NI',
        'NER' => 'NE',
        'NGA' => 'NG',
        'NIU' => 'NU',
        'NFK' => 'NF',
        'MNP' => 'MP',
        'NOR' => 'NO',
        'OMN' => 'OM',
        'PAK' => 'PK',
        'PLW' => 'PW',
        'PSE' => 'PS',
        'PAN' => 'PA',
        'PNG' => 'PG',
        'PRY' => 'PY',
        'PER' => 'PE',
        'PHL' => 'PH',
        'PCN' => 'PN',
        'POL' => 'PL',
        'PRT' => 'PT',
        'PRI' => 'PR',
        'QAT' => 'QA',
        'REU' => 'RE',
        'ROU' => 'RO',
        'RUS' => 'RU',
        'RWA' => 'RW',
        'BLM' => 'BL',
        'SHN' => 'SH',
        'KNA' => 'KN',
        'LCA' => 'LC',
        'MAF' => 'MF',
        'SPM' => 'PM',
        'VCT' => 'VC',
        'WSM' => 'WS',
        'SMR' => 'SM',
        'STP' => 'ST',
        'SAU' => 'SA',
        'SEN' => 'SN',
        'SRB' => 'RS',
        'SYC' => 'SC',
        'SLE' => 'SL',
        'SGP' => 'SG',
        'SXM' => 'SX',
        'SVK' => 'SK',
        'SVN' => 'SI',
        'SLB' => 'SB',
        'SOM' => 'SO',
        'ZAF' => 'ZA',
        'SGS' => 'GS',
        'SSD' => 'SS',
        'ESP' => 'ES',
        'LKA' => 'LK',
        'SDN' => 'SD',
        'SUR' => 'SR',
        'SJM' => 'SJ',
        'SWZ' => 'SZ',
        'SWE' => 'SE',
        'CHE' => 'CH',
        'SYR' => 'SY',
        'TWN' => 'TW',
        'TJK' => 'TJ',
        'TZA' => 'TZ',
        'THA' => 'TH',
        'TLS' => 'TL',
        'TGO' => 'TG',
        'TKL' => 'TK',
        'TON' => 'TO',
        'TTO' => 'TT',
        'TUN' => 'TN',
        'TUR' => 'TR',
        'TKM' => 'TM',
        'TCA' => 'TC',
        'TUV' => 'TV',
        'UGA' => 'UG',
        'UKR' => 'UA',
        'ARE' => 'AE',
        'GBR' => 'GB',
        'UMI' => 'UM',
        'USA' => 'US',
        'URY' => 'UY',
        'UZB' => 'UZ',
        'VUT' => 'VU',
        'VEN' => 'VE',
        'VNM' => 'VN',
        'VGB' => 'VG',
        'VIR' => 'VI',
        'WLF' => 'WF',
        'ESH' => 'EH',
        'YEM' => 'YE',
        'ZMB' => 'ZM',
        'ZWE' => 'ZW',
    ];

    /**
     * Index of numeric3 codes to speed the lookup.
     *
     * @var array
     */
    private static $numeric3Index = [
        '004' => 'AF',
        248 => 'AX',
        '008' => 'AL',
        '012' => 'DZ',
        '016' => 'AS',
        '020' => 'AD',
        '024' => 'AO',
        660 => 'AI',
        '010' => 'AQ',
        '028' => 'AG',
        '032' => 'AR',
        '051' => 'AM',
        533 => 'AW',
        '036' => 'AU',
        '040' => 'AT',
        '031' => 'AZ',
        '044' => 'BS',
        '048' => 'BH',
        '050' => 'BD',
        '052' => 'BB',
        112 => 'BY',
        '056' => 'BE',
        '084' => 'BZ',
        204 => 'BJ',
        '060' => 'BM',
        '064' => 'BT',
        '068' => 'BO',
        535 => 'BQ',
        '070' => 'BA',
        '072' => 'BW',
        '074' => 'BV',
        '076' => 'BR',
        '086' => 'IO',
        '096' => 'BN',
        100 => 'BG',
        854 => 'BF',
        108 => 'BI',
        132 => 'CV',
        116 => 'KH',
        120 => 'CM',
        124 => 'CA',
        136 => 'KY',
        140 => 'CF',
        148 => 'TD',
        152 => 'CL',
        156 => 'CN',
        162 => 'CX',
        166 => 'CC',
        170 => 'CO',
        174 => 'KM',
        180 => 'CD',
        178 => 'CG',
        184 => 'CK',
        188 => 'CR',
        384 => 'CI',
        191 => 'HR',
        192 => 'CU',
        531 => 'CW',
        196 => 'CY',
        203 => 'CZ',
        208 => 'DK',
        262 => 'DJ',
        212 => 'DM',
        214 => 'DO',
        218 => 'EC',
        818 => 'EG',
        222 => 'SV',
        226 => 'GQ',
        232 => 'ER',
        233 => 'EE',
        231 => 'ET',
        238 => 'FK',
        234 => 'FO',
        242 => 'FJ',
        246 => 'FI',
        250 => 'FR',
        254 => 'GF',
        258 => 'PF',
        260 => 'TF',
        266 => 'GA',
        270 => 'GM',
        268 => 'GE',
        276 => 'DE',
        288 => 'GH',
        292 => 'GI',
        300 => 'GR',
        304 => 'GL',
        308 => 'GD',
        312 => 'GP',
        316 => 'GU',
        320 => 'GT',
        831 => 'GG',
        324 => 'GN',
        624 => 'GW',
        328 => 'GY',
        332 => 'HT',
        334 => 'HM',
        336 => 'VA',
        340 => 'HN',
        344 => 'HK',
        348 => 'HU',
        352 => 'IS',
        356 => 'IN',
        360 => 'ID',
        364 => 'IR',
        368 => 'IQ',
        372 => 'IE',
        833 => 'IM',
        376 => 'IL',
        380 => 'IT',
        388 => 'JM',
        392 => 'JP',
        832 => 'JE',
        400 => 'JO',
        398 => 'KZ',
        404 => 'KE',
        296 => 'KI',
        408 => 'KP',
        410 => 'KR',
        414 => 'KW',
        417 => 'KG',
        418 => 'LA',
        428 => 'LV',
        422 => 'LB',
        426 => 'LS',
        430 => 'LR',
        434 => 'LY',
        438 => 'LI',
        440 => 'LT',
        442 => 'LU',
        446 => 'MO',
        807 => 'MK',
        450 => 'MG',
        454 => 'MW',
        458 => 'MY',
        462 => 'MV',
        466 => 'ML',
        470 => 'MT',
        584 => 'MH',
        474 => 'MQ',
        478 => 'MR',
        480 => 'MU',
        175 => 'YT',
        484 => 'MX',
        583 => 'FM',
        498 => 'MD',
        492 => 'MC',
        496 => 'MN',
        499 => 'ME',
        500 => 'MS',
        504 => 'MA',
        508 => 'MZ',
        104 => 'MM',
        516 => 'NA',
        520 => 'NR',
        524 => 'NP',
        528 => 'NL',
        540 => 'NC',
        554 => 'NZ',
        558 => 'NI',
        562 => 'NE',
        566 => 'NG',
        570 => 'NU',
        574 => 'NF',
        580 => 'MP',
        578 => 'NO',
        512 => 'OM',
        586 => 'PK',
        585 => 'PW',
        275 => 'PS',
        591 => 'PA',
        598 => 'PG',
        600 => 'PY',
        604 => 'PE',
        608 => 'PH',
        612 => 'PN',
        616 => 'PL',
        620 => 'PT',
        630 => 'PR',
        634 => 'QA',
        638 => 'RE',
        642 => 'RO',
        643 => 'RU',
        646 => 'RW',
        652 => 'BL',
        654 => 'SH',
        659 => 'KN',
        662 => 'LC',
        663 => 'MF',
        666 => 'PM',
        670 => 'VC',
        882 => 'WS',
        674 => 'SM',
        678 => 'ST',
        682 => 'SA',
        686 => 'SN',
        688 => 'RS',
        690 => 'SC',
        694 => 'SL',
        702 => 'SG',
        534 => 'SX',
        703 => 'SK',
        705 => 'SI',
        '090' => 'SB',
        706 => 'SO',
        710 => 'ZA',
        239 => 'GS',
        728 => 'SS',
        724 => 'ES',
        144 => 'LK',
        729 => 'SD',
        740 => 'SR',
        744 => 'SJ',
        748 => 'SZ',
        752 => 'SE',
        756 => 'CH',
        760 => 'SY',
        158 => 'TW',
        762 => 'TJ',
        834 => 'TZ',
        764 => 'TH',
        626 => 'TL',
        768 => 'TG',
        772 => 'TK',
        776 => 'TO',
        780 => 'TT',
        788 => 'TN',
        792 => 'TR',
        795 => 'TM',
        796 => 'TC',
        798 => 'TV',
        800 => 'UG',
        804 => 'UA',
        784 => 'AE',
        826 => 'GB',
        581 => 'UM',
        840 => 'US',
        858 => 'UY',
        860 => 'UZ',
        548 => 'VU',
        862 => 'VE',
        704 => 'VN',
        '092' => 'VG',
        850 => 'VI',
        876 => 'WF',
        732 => 'EH',
        887 => 'YE',
        894 => 'ZM',
        716 => 'ZW',
    ];

    /**
     * Magic method to redirect calls to object methods towards static methods.
     *
     * @param string $method
     * @param array $args
     * @return array
     */
    public function __call($method, $args)
    {
        if (!method_exists($this, $method)) {
            throw new BadMethodCallException;
        }

        return forward_static_call_array([static::class, $method], $args);
    }

    /**
     * Returns true if code is a known identifier.
     *
     * @param mixed $code
     * @return boolean
     */
    public static function exists($code)
    {
        try {
            static::get($code);
        } catch (OutOfBoundsException $e) {
            return false;
        }

        return true;
    }

    /**
     * Try all methods for a result.
     *
     * @param mixed $code
     * @return array
     */
    public static function get($code)
    {
        try {
            return static::getByAlpha2($code);
        } catch (OutOfBoundsException $e) {
            try {
                return static::getByAlpha3($code);
            } catch (OutOfBoundsException $e) {
                try {
                    return static::getByNumeric3($code);
                } catch (OutOfBoundsException $e) {
                    throw new OutOfBoundsException("The code \"{$code}\" is not listed in ISO 4217");
                }
            }
        }
    }

    /**
     * Find and return country by its alphabetic two-character identifier.
     *
     * @param string $alpha2
     * @return array
     */
    public static function getByAlpha2($alpha2)
    {
        $alpha2 = strtoupper($alpha2);

        if (!isset(static::$countries[$alpha2])) {
            throw new OutOfBoundsException("The 2 character alpha code \"$alpha2\" is not listed in ISO 3166");
        }

        return new Country(static::$countries[$alpha2]);
    }

    /**
     * Find and return country by its alphabetic three-character identifier.
     *
     * @param string $alpha3
     * @return array
     */
    public static function getByAlpha3($alpha3)
    {
        $alpha3 = strtoupper($alpha3);

        if (!isset(static::$alpha3Index[$alpha3])) {
            throw new OutOfBoundsException("The 3 character alpha code \"$alpha3\" is not listed in ISO 3166");
        }

        return new Country(static::$countries[static::$alpha3Index[$alpha3]]);
    }

    /**
     * Find and return country by its numeric three-character identifier.
     *
     * @param string $numeric3
     * @return array
     */
    public static function getByNumeric3($numeric3)
    {
        $numeric3 = strtoupper($numeric3);

        if (!isset(static::$numeric3Index[$numeric3])) {
            throw new OutOfBoundsException("The 3 character numeric code \"$numeric3\" is not listed in ISO 3166");
        }

        return new Country(static::$countries[static::$numeric3Index[$numeric3]]);
    }

    /**
     * Return all countries as a numerically-keyed array.
     *
     * @return array
     */
    public static function all()
    {
        return array_values(static::$countries);
    }
}
